# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/elee/repos/MotorMC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/elee/repos/MotorMC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elee/repos/MotorMC/CMakeFiles /home/elee/repos/MotorMC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/elee/repos/MotorMC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MotorMC

# Build rule for target.
MotorMC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MotorMC
.PHONY : MotorMC

# fast build rule for target.
MotorMC/fast:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/build
.PHONY : MotorMC/fast

src/crypt/cfb8.o: src/crypt/cfb8.c.o

.PHONY : src/crypt/cfb8.o

# target to build an object file
src/crypt/cfb8.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/cfb8.c.o
.PHONY : src/crypt/cfb8.c.o

src/crypt/cfb8.i: src/crypt/cfb8.c.i

.PHONY : src/crypt/cfb8.i

# target to preprocess a source file
src/crypt/cfb8.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/cfb8.c.i
.PHONY : src/crypt/cfb8.c.i

src/crypt/cfb8.s: src/crypt/cfb8.c.s

.PHONY : src/crypt/cfb8.s

# target to generate assembly for a file
src/crypt/cfb8.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/cfb8.c.s
.PHONY : src/crypt/cfb8.c.s

src/crypt/random.o: src/crypt/random.c.o

.PHONY : src/crypt/random.o

# target to build an object file
src/crypt/random.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/random.c.o
.PHONY : src/crypt/random.c.o

src/crypt/random.i: src/crypt/random.c.i

.PHONY : src/crypt/random.i

# target to preprocess a source file
src/crypt/random.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/random.c.i
.PHONY : src/crypt/random.c.i

src/crypt/random.s: src/crypt/random.c.s

.PHONY : src/crypt/random.s

# target to generate assembly for a file
src/crypt/random.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/random.c.s
.PHONY : src/crypt/random.c.s

src/crypt/rsa.o: src/crypt/rsa.c.o

.PHONY : src/crypt/rsa.o

# target to build an object file
src/crypt/rsa.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/rsa.c.o
.PHONY : src/crypt/rsa.c.o

src/crypt/rsa.i: src/crypt/rsa.c.i

.PHONY : src/crypt/rsa.i

# target to preprocess a source file
src/crypt/rsa.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/rsa.c.i
.PHONY : src/crypt/rsa.c.i

src/crypt/rsa.s: src/crypt/rsa.c.s

.PHONY : src/crypt/rsa.s

# target to generate assembly for a file
src/crypt/rsa.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/crypt/rsa.c.s
.PHONY : src/crypt/rsa.c.s

src/io/chat/chat.o: src/io/chat/chat.c.o

.PHONY : src/io/chat/chat.o

# target to build an object file
src/io/chat/chat.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/chat/chat.c.o
.PHONY : src/io/chat/chat.c.o

src/io/chat/chat.i: src/io/chat/chat.c.i

.PHONY : src/io/chat/chat.i

# target to preprocess a source file
src/io/chat/chat.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/chat/chat.c.i
.PHONY : src/io/chat/chat.c.i

src/io/chat/chat.s: src/io/chat/chat.c.s

.PHONY : src/io/chat/chat.s

# target to generate assembly for a file
src/io/chat/chat.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/chat/chat.c.s
.PHONY : src/io/chat/chat.c.s

src/io/chat/translation.o: src/io/chat/translation.c.o

.PHONY : src/io/chat/translation.o

# target to build an object file
src/io/chat/translation.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/chat/translation.c.o
.PHONY : src/io/chat/translation.c.o

src/io/chat/translation.i: src/io/chat/translation.c.i

.PHONY : src/io/chat/translation.i

# target to preprocess a source file
src/io/chat/translation.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/chat/translation.c.i
.PHONY : src/io/chat/translation.c.i

src/io/chat/translation.s: src/io/chat/translation.c.s

.PHONY : src/io/chat/translation.s

# target to generate assembly for a file
src/io/chat/translation.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/chat/translation.c.s
.PHONY : src/io/chat/translation.c.s

src/io/commands/commands.o: src/io/commands/commands.c.o

.PHONY : src/io/commands/commands.o

# target to build an object file
src/io/commands/commands.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/commands/commands.c.o
.PHONY : src/io/commands/commands.c.o

src/io/commands/commands.i: src/io/commands/commands.c.i

.PHONY : src/io/commands/commands.i

# target to preprocess a source file
src/io/commands/commands.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/commands/commands.c.i
.PHONY : src/io/commands/commands.c.i

src/io/commands/commands.s: src/io/commands/commands.c.s

.PHONY : src/io/commands/commands.s

# target to generate assembly for a file
src/io/commands/commands.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/commands/commands.c.s
.PHONY : src/io/commands/commands.c.s

src/io/commands/graph.o: src/io/commands/graph.c.o

.PHONY : src/io/commands/graph.o

# target to build an object file
src/io/commands/graph.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/commands/graph.c.o
.PHONY : src/io/commands/graph.c.o

src/io/commands/graph.i: src/io/commands/graph.c.i

.PHONY : src/io/commands/graph.i

# target to preprocess a source file
src/io/commands/graph.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/commands/graph.c.i
.PHONY : src/io/commands/graph.c.i

src/io/commands/graph.s: src/io/commands/graph.c.s

.PHONY : src/io/commands/graph.s

# target to generate assembly for a file
src/io/commands/graph.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/commands/graph.c.s
.PHONY : src/io/commands/graph.c.s

src/io/filesystem/filesystem.o: src/io/filesystem/filesystem.c.o

.PHONY : src/io/filesystem/filesystem.o

# target to build an object file
src/io/filesystem/filesystem.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/filesystem/filesystem.c.o
.PHONY : src/io/filesystem/filesystem.c.o

src/io/filesystem/filesystem.i: src/io/filesystem/filesystem.c.i

.PHONY : src/io/filesystem/filesystem.i

# target to preprocess a source file
src/io/filesystem/filesystem.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/filesystem/filesystem.c.i
.PHONY : src/io/filesystem/filesystem.c.i

src/io/filesystem/filesystem.s: src/io/filesystem/filesystem.c.s

.PHONY : src/io/filesystem/filesystem.s

# target to generate assembly for a file
src/io/filesystem/filesystem.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/filesystem/filesystem.c.s
.PHONY : src/io/filesystem/filesystem.c.s

src/io/json/mjson.o: src/io/json/mjson.c.o

.PHONY : src/io/json/mjson.o

# target to build an object file
src/io/json/mjson.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/json/mjson.c.o
.PHONY : src/io/json/mjson.c.o

src/io/json/mjson.i: src/io/json/mjson.c.i

.PHONY : src/io/json/mjson.i

# target to preprocess a source file
src/io/json/mjson.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/json/mjson.c.i
.PHONY : src/io/json/mjson.c.i

src/io/json/mjson.s: src/io/json/mjson.c.s

.PHONY : src/io/json/mjson.s

# target to generate assembly for a file
src/io/json/mjson.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/json/mjson.c.s
.PHONY : src/io/json/mjson.c.s

src/io/logger/logger.o: src/io/logger/logger.c.o

.PHONY : src/io/logger/logger.o

# target to build an object file
src/io/logger/logger.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/logger/logger.c.o
.PHONY : src/io/logger/logger.c.o

src/io/logger/logger.i: src/io/logger/logger.c.i

.PHONY : src/io/logger/logger.i

# target to preprocess a source file
src/io/logger/logger.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/logger/logger.c.i
.PHONY : src/io/logger/logger.c.i

src/io/logger/logger.s: src/io/logger/logger.c.s

.PHONY : src/io/logger/logger.s

# target to generate assembly for a file
src/io/logger/logger.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/logger/logger.c.s
.PHONY : src/io/logger/logger.c.s

src/io/nbt/mnbt.o: src/io/nbt/mnbt.c.o

.PHONY : src/io/nbt/mnbt.o

# target to build an object file
src/io/nbt/mnbt.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/nbt/mnbt.c.o
.PHONY : src/io/nbt/mnbt.c.o

src/io/nbt/mnbt.i: src/io/nbt/mnbt.c.i

.PHONY : src/io/nbt/mnbt.i

# target to preprocess a source file
src/io/nbt/mnbt.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/nbt/mnbt.c.i
.PHONY : src/io/nbt/mnbt.c.i

src/io/nbt/mnbt.s: src/io/nbt/mnbt.c.s

.PHONY : src/io/nbt/mnbt.s

# target to generate assembly for a file
src/io/nbt/mnbt.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/nbt/mnbt.c.s
.PHONY : src/io/nbt/mnbt.c.s

src/io/packet/packet.o: src/io/packet/packet.c.o

.PHONY : src/io/packet/packet.o

# target to build an object file
src/io/packet/packet.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/packet/packet.c.o
.PHONY : src/io/packet/packet.c.o

src/io/packet/packet.i: src/io/packet/packet.c.i

.PHONY : src/io/packet/packet.i

# target to preprocess a source file
src/io/packet/packet.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/packet/packet.c.i
.PHONY : src/io/packet/packet.c.i

src/io/packet/packet.s: src/io/packet/packet.c.s

.PHONY : src/io/packet/packet.s

# target to generate assembly for a file
src/io/packet/packet.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/io/packet/packet.c.s
.PHONY : src/io/packet/packet.c.s

src/jobs/board.o: src/jobs/board.c.o

.PHONY : src/jobs/board.o

# target to build an object file
src/jobs/board.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/board.c.o
.PHONY : src/jobs/board.c.o

src/jobs/board.i: src/jobs/board.c.i

.PHONY : src/jobs/board.i

# target to preprocess a source file
src/jobs/board.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/board.c.i
.PHONY : src/jobs/board.c.i

src/jobs/board.s: src/jobs/board.c.s

.PHONY : src/jobs/board.s

# target to generate assembly for a file
src/jobs/board.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/board.c.s
.PHONY : src/jobs/board.c.s

src/jobs/handlers.o: src/jobs/handlers.c.o

.PHONY : src/jobs/handlers.o

# target to build an object file
src/jobs/handlers.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/handlers.c.o
.PHONY : src/jobs/handlers.c.o

src/jobs/handlers.i: src/jobs/handlers.c.i

.PHONY : src/jobs/handlers.i

# target to preprocess a source file
src/jobs/handlers.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/handlers.c.i
.PHONY : src/jobs/handlers.c.i

src/jobs/handlers.s: src/jobs/handlers.c.s

.PHONY : src/jobs/handlers.s

# target to generate assembly for a file
src/jobs/handlers.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/handlers.c.s
.PHONY : src/jobs/handlers.c.s

src/jobs/scheduler/scheduler.o: src/jobs/scheduler/scheduler.c.o

.PHONY : src/jobs/scheduler/scheduler.o

# target to build an object file
src/jobs/scheduler/scheduler.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/scheduler/scheduler.c.o
.PHONY : src/jobs/scheduler/scheduler.c.o

src/jobs/scheduler/scheduler.i: src/jobs/scheduler/scheduler.c.i

.PHONY : src/jobs/scheduler/scheduler.i

# target to preprocess a source file
src/jobs/scheduler/scheduler.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/scheduler/scheduler.c.i
.PHONY : src/jobs/scheduler/scheduler.c.i

src/jobs/scheduler/scheduler.s: src/jobs/scheduler/scheduler.c.s

.PHONY : src/jobs/scheduler/scheduler.s

# target to generate assembly for a file
src/jobs/scheduler/scheduler.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/jobs/scheduler/scheduler.c.s
.PHONY : src/jobs/scheduler/scheduler.c.s

src/listening/listening.o: src/listening/listening.c.o

.PHONY : src/listening/listening.o

# target to build an object file
src/listening/listening.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/listening.c.o
.PHONY : src/listening/listening.c.o

src/listening/listening.i: src/listening/listening.c.i

.PHONY : src/listening/listening.i

# target to preprocess a source file
src/listening/listening.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/listening.c.i
.PHONY : src/listening/listening.c.i

src/listening/listening.s: src/listening/listening.c.s

.PHONY : src/listening/listening.s

# target to generate assembly for a file
src/listening/listening.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/listening.c.s
.PHONY : src/listening/listening.c.s

src/listening/phd/handshake.o: src/listening/phd/handshake.c.o

.PHONY : src/listening/phd/handshake.o

# target to build an object file
src/listening/phd/handshake.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/handshake.c.o
.PHONY : src/listening/phd/handshake.c.o

src/listening/phd/handshake.i: src/listening/phd/handshake.c.i

.PHONY : src/listening/phd/handshake.i

# target to preprocess a source file
src/listening/phd/handshake.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/handshake.c.i
.PHONY : src/listening/phd/handshake.c.i

src/listening/phd/handshake.s: src/listening/phd/handshake.c.s

.PHONY : src/listening/phd/handshake.s

# target to generate assembly for a file
src/listening/phd/handshake.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/handshake.c.s
.PHONY : src/listening/phd/handshake.c.s

src/listening/phd/login.o: src/listening/phd/login.c.o

.PHONY : src/listening/phd/login.o

# target to build an object file
src/listening/phd/login.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/login.c.o
.PHONY : src/listening/phd/login.c.o

src/listening/phd/login.i: src/listening/phd/login.c.i

.PHONY : src/listening/phd/login.i

# target to preprocess a source file
src/listening/phd/login.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/login.c.i
.PHONY : src/listening/phd/login.c.i

src/listening/phd/login.s: src/listening/phd/login.c.s

.PHONY : src/listening/phd/login.s

# target to generate assembly for a file
src/listening/phd/login.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/login.c.s
.PHONY : src/listening/phd/login.c.s

src/listening/phd/play.o: src/listening/phd/play.c.o

.PHONY : src/listening/phd/play.o

# target to build an object file
src/listening/phd/play.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/play.c.o
.PHONY : src/listening/phd/play.c.o

src/listening/phd/play.i: src/listening/phd/play.c.i

.PHONY : src/listening/phd/play.i

# target to preprocess a source file
src/listening/phd/play.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/play.c.i
.PHONY : src/listening/phd/play.c.i

src/listening/phd/play.s: src/listening/phd/play.c.s

.PHONY : src/listening/phd/play.s

# target to generate assembly for a file
src/listening/phd/play.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/play.c.s
.PHONY : src/listening/phd/play.c.s

src/listening/phd/status.o: src/listening/phd/status.c.o

.PHONY : src/listening/phd/status.o

# target to build an object file
src/listening/phd/status.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/status.c.o
.PHONY : src/listening/phd/status.c.o

src/listening/phd/status.i: src/listening/phd/status.c.i

.PHONY : src/listening/phd/status.i

# target to preprocess a source file
src/listening/phd/status.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/status.c.i
.PHONY : src/listening/phd/status.c.i

src/listening/phd/status.s: src/listening/phd/status.c.s

.PHONY : src/listening/phd/status.s

# target to generate assembly for a file
src/listening/phd/status.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/phd/status.c.s
.PHONY : src/listening/phd/status.c.s

src/listening/socket/socket.o: src/listening/socket/socket.c.o

.PHONY : src/listening/socket/socket.o

# target to build an object file
src/listening/socket/socket.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/socket/socket.c.o
.PHONY : src/listening/socket/socket.c.o

src/listening/socket/socket.i: src/listening/socket/socket.c.i

.PHONY : src/listening/socket/socket.i

# target to preprocess a source file
src/listening/socket/socket.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/socket/socket.c.i
.PHONY : src/listening/socket/socket.c.i

src/listening/socket/socket.s: src/listening/socket/socket.c.s

.PHONY : src/listening/socket/socket.s

# target to generate assembly for a file
src/listening/socket/socket.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/listening/socket/socket.c.s
.PHONY : src/listening/socket/socket.c.s

src/motor.o: src/motor.c.o

.PHONY : src/motor.o

# target to build an object file
src/motor.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/motor.c.o
.PHONY : src/motor.c.o

src/motor.i: src/motor.c.i

.PHONY : src/motor.i

# target to preprocess a source file
src/motor.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/motor.c.i
.PHONY : src/motor.c.i

src/motor.s: src/motor.c.s

.PHONY : src/motor.s

# target to generate assembly for a file
src/motor.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/motor.c.s
.PHONY : src/motor.c.s

src/plugin/manager.o: src/plugin/manager.c.o

.PHONY : src/plugin/manager.o

# target to build an object file
src/plugin/manager.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/plugin/manager.c.o
.PHONY : src/plugin/manager.c.o

src/plugin/manager.i: src/plugin/manager.c.i

.PHONY : src/plugin/manager.i

# target to preprocess a source file
src/plugin/manager.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/plugin/manager.c.i
.PHONY : src/plugin/manager.c.i

src/plugin/manager.s: src/plugin/manager.c.s

.PHONY : src/plugin/manager.s

# target to generate assembly for a file
src/plugin/manager.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/plugin/manager.c.s
.PHONY : src/plugin/manager.c.s

src/test/tests.o: src/test/tests.c.o

.PHONY : src/test/tests.o

# target to build an object file
src/test/tests.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/test/tests.c.o
.PHONY : src/test/tests.c.o

src/test/tests.i: src/test/tests.c.i

.PHONY : src/test/tests.i

# target to preprocess a source file
src/test/tests.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/test/tests.c.i
.PHONY : src/test/tests.c.i

src/test/tests.s: src/test/tests.c.s

.PHONY : src/test/tests.s

# target to generate assembly for a file
src/test/tests.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/test/tests.c.s
.PHONY : src/test/tests.c.s

src/util/ansi_escapes.o: src/util/ansi_escapes.c.o

.PHONY : src/util/ansi_escapes.o

# target to build an object file
src/util/ansi_escapes.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/ansi_escapes.c.o
.PHONY : src/util/ansi_escapes.c.o

src/util/ansi_escapes.i: src/util/ansi_escapes.c.i

.PHONY : src/util/ansi_escapes.i

# target to preprocess a source file
src/util/ansi_escapes.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/ansi_escapes.c.i
.PHONY : src/util/ansi_escapes.c.i

src/util/ansi_escapes.s: src/util/ansi_escapes.c.s

.PHONY : src/util/ansi_escapes.s

# target to generate assembly for a file
src/util/ansi_escapes.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/ansi_escapes.c.s
.PHONY : src/util/ansi_escapes.c.s

src/util/dll.o: src/util/dll.c.o

.PHONY : src/util/dll.o

# target to build an object file
src/util/dll.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/dll.c.o
.PHONY : src/util/dll.c.o

src/util/dll.i: src/util/dll.c.i

.PHONY : src/util/dll.i

# target to preprocess a source file
src/util/dll.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/dll.c.i
.PHONY : src/util/dll.c.i

src/util/dll.s: src/util/dll.c.s

.PHONY : src/util/dll.s

# target to generate assembly for a file
src/util/dll.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/dll.c.s
.PHONY : src/util/dll.c.s

src/util/list.o: src/util/list.c.o

.PHONY : src/util/list.o

# target to build an object file
src/util/list.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/list.c.o
.PHONY : src/util/list.c.o

src/util/list.i: src/util/list.c.i

.PHONY : src/util/list.i

# target to preprocess a source file
src/util/list.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/list.c.i
.PHONY : src/util/list.c.i

src/util/list.s: src/util/list.c.s

.PHONY : src/util/list.s

# target to generate assembly for a file
src/util/list.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/list.c.s
.PHONY : src/util/list.c.s

src/util/tree.o: src/util/tree.c.o

.PHONY : src/util/tree.o

# target to build an object file
src/util/tree.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/tree.c.o
.PHONY : src/util/tree.c.o

src/util/tree.i: src/util/tree.c.i

.PHONY : src/util/tree.i

# target to preprocess a source file
src/util/tree.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/tree.c.i
.PHONY : src/util/tree.c.i

src/util/tree.s: src/util/tree.c.s

.PHONY : src/util/tree.s

# target to generate assembly for a file
src/util/tree.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/tree.c.s
.PHONY : src/util/tree.c.s

src/util/util.o: src/util/util.c.o

.PHONY : src/util/util.o

# target to build an object file
src/util/util.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/util.c.o
.PHONY : src/util/util.c.o

src/util/util.i: src/util/util.c.i

.PHONY : src/util/util.i

# target to preprocess a source file
src/util/util.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/util.c.i
.PHONY : src/util/util.c.i

src/util/util.s: src/util/util.c.s

.PHONY : src/util/util.s

# target to generate assembly for a file
src/util/util.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/util/util.c.s
.PHONY : src/util/util.c.s

src/world/entity/entity.o: src/world/entity/entity.c.o

.PHONY : src/world/entity/entity.o

# target to build an object file
src/world/entity/entity.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/entity.c.o
.PHONY : src/world/entity/entity.c.o

src/world/entity/entity.i: src/world/entity/entity.c.i

.PHONY : src/world/entity/entity.i

# target to preprocess a source file
src/world/entity/entity.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/entity.c.i
.PHONY : src/world/entity/entity.c.i

src/world/entity/entity.s: src/world/entity/entity.c.s

.PHONY : src/world/entity/entity.s

# target to generate assembly for a file
src/world/entity/entity.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/entity.c.s
.PHONY : src/world/entity/entity.c.s

src/world/entity/living/living.o: src/world/entity/living/living.c.o

.PHONY : src/world/entity/living/living.o

# target to build an object file
src/world/entity/living/living.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/living/living.c.o
.PHONY : src/world/entity/living/living.c.o

src/world/entity/living/living.i: src/world/entity/living/living.c.i

.PHONY : src/world/entity/living/living.i

# target to preprocess a source file
src/world/entity/living/living.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/living/living.c.i
.PHONY : src/world/entity/living/living.c.i

src/world/entity/living/living.s: src/world/entity/living/living.c.s

.PHONY : src/world/entity/living/living.s

# target to generate assembly for a file
src/world/entity/living/living.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/living/living.c.s
.PHONY : src/world/entity/living/living.c.s

src/world/entity/living/player/player.o: src/world/entity/living/player/player.c.o

.PHONY : src/world/entity/living/player/player.o

# target to build an object file
src/world/entity/living/player/player.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/living/player/player.c.o
.PHONY : src/world/entity/living/player/player.c.o

src/world/entity/living/player/player.i: src/world/entity/living/player/player.c.i

.PHONY : src/world/entity/living/player/player.i

# target to preprocess a source file
src/world/entity/living/player/player.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/living/player/player.c.i
.PHONY : src/world/entity/living/player/player.c.i

src/world/entity/living/player/player.s: src/world/entity/living/player/player.c.s

.PHONY : src/world/entity/living/player/player.s

# target to generate assembly for a file
src/world/entity/living/player/player.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/entity/living/player/player.c.s
.PHONY : src/world/entity/living/player/player.c.s

src/world/item/item.o: src/world/item/item.c.o

.PHONY : src/world/item/item.o

# target to build an object file
src/world/item/item.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/item/item.c.o
.PHONY : src/world/item/item.c.o

src/world/item/item.i: src/world/item/item.c.i

.PHONY : src/world/item/item.i

# target to preprocess a source file
src/world/item/item.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/item/item.c.i
.PHONY : src/world/item/item.c.i

src/world/item/item.s: src/world/item/item.c.s

.PHONY : src/world/item/item.s

# target to generate assembly for a file
src/world/item/item.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/item/item.c.s
.PHONY : src/world/item/item.c.s

src/world/item/recipe/recipe.o: src/world/item/recipe/recipe.c.o

.PHONY : src/world/item/recipe/recipe.o

# target to build an object file
src/world/item/recipe/recipe.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/item/recipe/recipe.c.o
.PHONY : src/world/item/recipe/recipe.c.o

src/world/item/recipe/recipe.i: src/world/item/recipe/recipe.c.i

.PHONY : src/world/item/recipe/recipe.i

# target to preprocess a source file
src/world/item/recipe/recipe.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/item/recipe/recipe.c.i
.PHONY : src/world/item/recipe/recipe.c.i

src/world/item/recipe/recipe.s: src/world/item/recipe/recipe.c.s

.PHONY : src/world/item/recipe/recipe.s

# target to generate assembly for a file
src/world/item/recipe/recipe.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/item/recipe/recipe.c.s
.PHONY : src/world/item/recipe/recipe.c.s

src/world/material/biomes.o: src/world/material/biomes.c.o

.PHONY : src/world/material/biomes.o

# target to build an object file
src/world/material/biomes.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/biomes.c.o
.PHONY : src/world/material/biomes.c.o

src/world/material/biomes.i: src/world/material/biomes.c.i

.PHONY : src/world/material/biomes.i

# target to preprocess a source file
src/world/material/biomes.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/biomes.c.i
.PHONY : src/world/material/biomes.c.i

src/world/material/biomes.s: src/world/material/biomes.c.s

.PHONY : src/world/material/biomes.s

# target to generate assembly for a file
src/world/material/biomes.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/biomes.c.s
.PHONY : src/world/material/biomes.c.s

src/world/material/blocks.o: src/world/material/blocks.c.o

.PHONY : src/world/material/blocks.o

# target to build an object file
src/world/material/blocks.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/blocks.c.o
.PHONY : src/world/material/blocks.c.o

src/world/material/blocks.i: src/world/material/blocks.c.i

.PHONY : src/world/material/blocks.i

# target to preprocess a source file
src/world/material/blocks.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/blocks.c.i
.PHONY : src/world/material/blocks.c.i

src/world/material/blocks.s: src/world/material/blocks.c.s

.PHONY : src/world/material/blocks.s

# target to generate assembly for a file
src/world/material/blocks.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/blocks.c.s
.PHONY : src/world/material/blocks.c.s

src/world/material/codec.o: src/world/material/codec.c.o

.PHONY : src/world/material/codec.o

# target to build an object file
src/world/material/codec.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/codec.c.o
.PHONY : src/world/material/codec.c.o

src/world/material/codec.i: src/world/material/codec.c.i

.PHONY : src/world/material/codec.i

# target to preprocess a source file
src/world/material/codec.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/codec.c.i
.PHONY : src/world/material/codec.c.i

src/world/material/codec.s: src/world/material/codec.c.s

.PHONY : src/world/material/codec.s

# target to generate assembly for a file
src/world/material/codec.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/codec.c.s
.PHONY : src/world/material/codec.c.s

src/world/material/dimensions.o: src/world/material/dimensions.c.o

.PHONY : src/world/material/dimensions.o

# target to build an object file
src/world/material/dimensions.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/dimensions.c.o
.PHONY : src/world/material/dimensions.c.o

src/world/material/dimensions.i: src/world/material/dimensions.c.i

.PHONY : src/world/material/dimensions.i

# target to preprocess a source file
src/world/material/dimensions.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/dimensions.c.i
.PHONY : src/world/material/dimensions.c.i

src/world/material/dimensions.s: src/world/material/dimensions.c.s

.PHONY : src/world/material/dimensions.s

# target to generate assembly for a file
src/world/material/dimensions.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/dimensions.c.s
.PHONY : src/world/material/dimensions.c.s

src/world/material/items.o: src/world/material/items.c.o

.PHONY : src/world/material/items.o

# target to build an object file
src/world/material/items.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/items.c.o
.PHONY : src/world/material/items.c.o

src/world/material/items.i: src/world/material/items.c.i

.PHONY : src/world/material/items.i

# target to preprocess a source file
src/world/material/items.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/items.c.i
.PHONY : src/world/material/items.c.i

src/world/material/items.s: src/world/material/items.c.s

.PHONY : src/world/material/items.s

# target to generate assembly for a file
src/world/material/items.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/items.c.s
.PHONY : src/world/material/items.c.s

src/world/material/state_modifiers.o: src/world/material/state_modifiers.c.o

.PHONY : src/world/material/state_modifiers.o

# target to build an object file
src/world/material/state_modifiers.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/state_modifiers.c.o
.PHONY : src/world/material/state_modifiers.c.o

src/world/material/state_modifiers.i: src/world/material/state_modifiers.c.i

.PHONY : src/world/material/state_modifiers.i

# target to preprocess a source file
src/world/material/state_modifiers.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/state_modifiers.c.i
.PHONY : src/world/material/state_modifiers.c.i

src/world/material/state_modifiers.s: src/world/material/state_modifiers.c.s

.PHONY : src/world/material/state_modifiers.s

# target to generate assembly for a file
src/world/material/state_modifiers.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/state_modifiers.c.s
.PHONY : src/world/material/state_modifiers.c.s

src/world/material/states.o: src/world/material/states.c.o

.PHONY : src/world/material/states.o

# target to build an object file
src/world/material/states.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/states.c.o
.PHONY : src/world/material/states.c.o

src/world/material/states.i: src/world/material/states.c.i

.PHONY : src/world/material/states.i

# target to preprocess a source file
src/world/material/states.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/states.c.i
.PHONY : src/world/material/states.c.i

src/world/material/states.s: src/world/material/states.c.s

.PHONY : src/world/material/states.s

# target to generate assembly for a file
src/world/material/states.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/states.c.s
.PHONY : src/world/material/states.c.s

src/world/material/tags/blocks.o: src/world/material/tags/blocks.c.o

.PHONY : src/world/material/tags/blocks.o

# target to build an object file
src/world/material/tags/blocks.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/blocks.c.o
.PHONY : src/world/material/tags/blocks.c.o

src/world/material/tags/blocks.i: src/world/material/tags/blocks.c.i

.PHONY : src/world/material/tags/blocks.i

# target to preprocess a source file
src/world/material/tags/blocks.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/blocks.c.i
.PHONY : src/world/material/tags/blocks.c.i

src/world/material/tags/blocks.s: src/world/material/tags/blocks.c.s

.PHONY : src/world/material/tags/blocks.s

# target to generate assembly for a file
src/world/material/tags/blocks.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/blocks.c.s
.PHONY : src/world/material/tags/blocks.c.s

src/world/material/tags/entity_types.o: src/world/material/tags/entity_types.c.o

.PHONY : src/world/material/tags/entity_types.o

# target to build an object file
src/world/material/tags/entity_types.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/entity_types.c.o
.PHONY : src/world/material/tags/entity_types.c.o

src/world/material/tags/entity_types.i: src/world/material/tags/entity_types.c.i

.PHONY : src/world/material/tags/entity_types.i

# target to preprocess a source file
src/world/material/tags/entity_types.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/entity_types.c.i
.PHONY : src/world/material/tags/entity_types.c.i

src/world/material/tags/entity_types.s: src/world/material/tags/entity_types.c.s

.PHONY : src/world/material/tags/entity_types.s

# target to generate assembly for a file
src/world/material/tags/entity_types.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/entity_types.c.s
.PHONY : src/world/material/tags/entity_types.c.s

src/world/material/tags/fluids.o: src/world/material/tags/fluids.c.o

.PHONY : src/world/material/tags/fluids.o

# target to build an object file
src/world/material/tags/fluids.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/fluids.c.o
.PHONY : src/world/material/tags/fluids.c.o

src/world/material/tags/fluids.i: src/world/material/tags/fluids.c.i

.PHONY : src/world/material/tags/fluids.i

# target to preprocess a source file
src/world/material/tags/fluids.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/fluids.c.i
.PHONY : src/world/material/tags/fluids.c.i

src/world/material/tags/fluids.s: src/world/material/tags/fluids.c.s

.PHONY : src/world/material/tags/fluids.s

# target to generate assembly for a file
src/world/material/tags/fluids.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/fluids.c.s
.PHONY : src/world/material/tags/fluids.c.s

src/world/material/tags/game_events.o: src/world/material/tags/game_events.c.o

.PHONY : src/world/material/tags/game_events.o

# target to build an object file
src/world/material/tags/game_events.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/game_events.c.o
.PHONY : src/world/material/tags/game_events.c.o

src/world/material/tags/game_events.i: src/world/material/tags/game_events.c.i

.PHONY : src/world/material/tags/game_events.i

# target to preprocess a source file
src/world/material/tags/game_events.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/game_events.c.i
.PHONY : src/world/material/tags/game_events.c.i

src/world/material/tags/game_events.s: src/world/material/tags/game_events.c.s

.PHONY : src/world/material/tags/game_events.s

# target to generate assembly for a file
src/world/material/tags/game_events.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/game_events.c.s
.PHONY : src/world/material/tags/game_events.c.s

src/world/material/tags/items.o: src/world/material/tags/items.c.o

.PHONY : src/world/material/tags/items.o

# target to build an object file
src/world/material/tags/items.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/items.c.o
.PHONY : src/world/material/tags/items.c.o

src/world/material/tags/items.i: src/world/material/tags/items.c.i

.PHONY : src/world/material/tags/items.i

# target to preprocess a source file
src/world/material/tags/items.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/items.c.i
.PHONY : src/world/material/tags/items.c.i

src/world/material/tags/items.s: src/world/material/tags/items.c.s

.PHONY : src/world/material/tags/items.s

# target to generate assembly for a file
src/world/material/tags/items.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/material/tags/items.c.s
.PHONY : src/world/material/tags/items.c.s

src/world/world.o: src/world/world.c.o

.PHONY : src/world/world.o

# target to build an object file
src/world/world.c.o:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/world.c.o
.PHONY : src/world/world.c.o

src/world/world.i: src/world/world.c.i

.PHONY : src/world/world.i

# target to preprocess a source file
src/world/world.c.i:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/world.c.i
.PHONY : src/world/world.c.i

src/world/world.s: src/world/world.c.s

.PHONY : src/world/world.s

# target to generate assembly for a file
src/world/world.c.s:
	$(MAKE) -f CMakeFiles/MotorMC.dir/build.make CMakeFiles/MotorMC.dir/src/world/world.c.s
.PHONY : src/world/world.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... MotorMC"
	@echo "... edit_cache"
	@echo "... src/crypt/cfb8.o"
	@echo "... src/crypt/cfb8.i"
	@echo "... src/crypt/cfb8.s"
	@echo "... src/crypt/random.o"
	@echo "... src/crypt/random.i"
	@echo "... src/crypt/random.s"
	@echo "... src/crypt/rsa.o"
	@echo "... src/crypt/rsa.i"
	@echo "... src/crypt/rsa.s"
	@echo "... src/io/chat/chat.o"
	@echo "... src/io/chat/chat.i"
	@echo "... src/io/chat/chat.s"
	@echo "... src/io/chat/translation.o"
	@echo "... src/io/chat/translation.i"
	@echo "... src/io/chat/translation.s"
	@echo "... src/io/commands/commands.o"
	@echo "... src/io/commands/commands.i"
	@echo "... src/io/commands/commands.s"
	@echo "... src/io/commands/graph.o"
	@echo "... src/io/commands/graph.i"
	@echo "... src/io/commands/graph.s"
	@echo "... src/io/filesystem/filesystem.o"
	@echo "... src/io/filesystem/filesystem.i"
	@echo "... src/io/filesystem/filesystem.s"
	@echo "... src/io/json/mjson.o"
	@echo "... src/io/json/mjson.i"
	@echo "... src/io/json/mjson.s"
	@echo "... src/io/logger/logger.o"
	@echo "... src/io/logger/logger.i"
	@echo "... src/io/logger/logger.s"
	@echo "... src/io/nbt/mnbt.o"
	@echo "... src/io/nbt/mnbt.i"
	@echo "... src/io/nbt/mnbt.s"
	@echo "... src/io/packet/packet.o"
	@echo "... src/io/packet/packet.i"
	@echo "... src/io/packet/packet.s"
	@echo "... src/jobs/board.o"
	@echo "... src/jobs/board.i"
	@echo "... src/jobs/board.s"
	@echo "... src/jobs/handlers.o"
	@echo "... src/jobs/handlers.i"
	@echo "... src/jobs/handlers.s"
	@echo "... src/jobs/scheduler/scheduler.o"
	@echo "... src/jobs/scheduler/scheduler.i"
	@echo "... src/jobs/scheduler/scheduler.s"
	@echo "... src/listening/listening.o"
	@echo "... src/listening/listening.i"
	@echo "... src/listening/listening.s"
	@echo "... src/listening/phd/handshake.o"
	@echo "... src/listening/phd/handshake.i"
	@echo "... src/listening/phd/handshake.s"
	@echo "... src/listening/phd/login.o"
	@echo "... src/listening/phd/login.i"
	@echo "... src/listening/phd/login.s"
	@echo "... src/listening/phd/play.o"
	@echo "... src/listening/phd/play.i"
	@echo "... src/listening/phd/play.s"
	@echo "... src/listening/phd/status.o"
	@echo "... src/listening/phd/status.i"
	@echo "... src/listening/phd/status.s"
	@echo "... src/listening/socket/socket.o"
	@echo "... src/listening/socket/socket.i"
	@echo "... src/listening/socket/socket.s"
	@echo "... src/motor.o"
	@echo "... src/motor.i"
	@echo "... src/motor.s"
	@echo "... src/plugin/manager.o"
	@echo "... src/plugin/manager.i"
	@echo "... src/plugin/manager.s"
	@echo "... src/test/tests.o"
	@echo "... src/test/tests.i"
	@echo "... src/test/tests.s"
	@echo "... src/util/ansi_escapes.o"
	@echo "... src/util/ansi_escapes.i"
	@echo "... src/util/ansi_escapes.s"
	@echo "... src/util/dll.o"
	@echo "... src/util/dll.i"
	@echo "... src/util/dll.s"
	@echo "... src/util/list.o"
	@echo "... src/util/list.i"
	@echo "... src/util/list.s"
	@echo "... src/util/tree.o"
	@echo "... src/util/tree.i"
	@echo "... src/util/tree.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
	@echo "... src/world/entity/entity.o"
	@echo "... src/world/entity/entity.i"
	@echo "... src/world/entity/entity.s"
	@echo "... src/world/entity/living/living.o"
	@echo "... src/world/entity/living/living.i"
	@echo "... src/world/entity/living/living.s"
	@echo "... src/world/entity/living/player/player.o"
	@echo "... src/world/entity/living/player/player.i"
	@echo "... src/world/entity/living/player/player.s"
	@echo "... src/world/item/item.o"
	@echo "... src/world/item/item.i"
	@echo "... src/world/item/item.s"
	@echo "... src/world/item/recipe/recipe.o"
	@echo "... src/world/item/recipe/recipe.i"
	@echo "... src/world/item/recipe/recipe.s"
	@echo "... src/world/material/biomes.o"
	@echo "... src/world/material/biomes.i"
	@echo "... src/world/material/biomes.s"
	@echo "... src/world/material/blocks.o"
	@echo "... src/world/material/blocks.i"
	@echo "... src/world/material/blocks.s"
	@echo "... src/world/material/codec.o"
	@echo "... src/world/material/codec.i"
	@echo "... src/world/material/codec.s"
	@echo "... src/world/material/dimensions.o"
	@echo "... src/world/material/dimensions.i"
	@echo "... src/world/material/dimensions.s"
	@echo "... src/world/material/items.o"
	@echo "... src/world/material/items.i"
	@echo "... src/world/material/items.s"
	@echo "... src/world/material/state_modifiers.o"
	@echo "... src/world/material/state_modifiers.i"
	@echo "... src/world/material/state_modifiers.s"
	@echo "... src/world/material/states.o"
	@echo "... src/world/material/states.i"
	@echo "... src/world/material/states.s"
	@echo "... src/world/material/tags/blocks.o"
	@echo "... src/world/material/tags/blocks.i"
	@echo "... src/world/material/tags/blocks.s"
	@echo "... src/world/material/tags/entity_types.o"
	@echo "... src/world/material/tags/entity_types.i"
	@echo "... src/world/material/tags/entity_types.s"
	@echo "... src/world/material/tags/fluids.o"
	@echo "... src/world/material/tags/fluids.i"
	@echo "... src/world/material/tags/fluids.s"
	@echo "... src/world/material/tags/game_events.o"
	@echo "... src/world/material/tags/game_events.i"
	@echo "... src/world/material/tags/game_events.s"
	@echo "... src/world/material/tags/items.o"
	@echo "... src/world/material/tags/items.i"
	@echo "... src/world/material/tags/items.s"
	@echo "... src/world/world.o"
	@echo "... src/world/world.i"
	@echo "... src/world/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

